## $Id: Makefile,v 1.1 2003/09/09 01:24:12 belaban Exp $

include ../../../../Makefile.include

vpath %.class $(CLASSDIR)/util



CLASSES=Command.class				\
	Util.class				\
	LinkedListQueue.class			\
	List.class				\
	Promise.class				\
	QueueClosedException.class		\
	Queue.class				\
	RWLock.class				\
	Marshaller.class			\
	Proxy1_4.class				\
	Range.class				\
	ReusableThread.class			\
	Rsp.class				\
	RspList.class				\
	SchedulerListener.class			\
	Stack.class				\
	ThreadPool.class			\
	Scheduler.class				\
	TimeScheduler.class			\
	TimedWriter.class			\
	PrintXMLTree.class



this: $(CLASSES)



clean: 
	@rm -f $(CLASSDIR)/util/*.class *~






