## $Id: Makefile,v 1.1.1.1 2003/09/09 01:24:11 belaban Exp $

include ../../../../../Makefile.include

vpath %.class $(CLASSDIR)/protocols/pbcast

CLASSFILES=ClientGmsImpl.class			\
	CoordGmsImpl.class			\
	Digest.class				\
	FD.class				\
	GMS.class				\
	GmsImpl.class				\
	Gossip.class				\
	JoinRsp.class				\
	MergeData.class				\
	NAKACK.class				\
	NakAckHeader.class			\
	PBCAST.class				\
	ParticipantGmsImpl.class		\
	PbcastHeader.class			\
	STABLE.class				\
	STATE_TRANSFER.class


all: $(CLASSFILES)



clean: 
	@rm -f $(CLASSDIR)/protocols/pbcast/*.class *~ core







