## $Id: Makefile,v 1.1 2003/09/09 01:24:08 belaban Exp $

include ../../../../Makefile.include


vpath %.class $(CLASSDIR)/conf



CLASSES=ClassConfigurator.class			\
        ClassMap.class				\
	ClassPathEntityResolver.class		\
	ConfiguratorFactory.class		\
	MagicNumberReader.class			\
	PlainConfigurator.class			\
	ProtocolData.class			\
	ProtocolParameter.class			\
	ProtocolStackConfigurator.class		\
	XmlConfigurator.class			\
	XmlValidator.class

all: $(CLASSES)



clean: 
	@rm -f $(CLASSDIR)/conf/*.class *~






