## $Id: Makefile,v 1.1.1.1 2003/09/09 01:24:09 belaban Exp $

include ../../../../../Makefile.include


vpath %.class $(CLASSDIR)/demos/applets


CLASSES=DrawApplet.class


all: $(CLASSES)


clean: 
	@rm -f $(CLASSDIR)/demos/applets/*.class *~ core





