## $Id: Makefile,v 1.1 2003/09/09 01:24:08 belaban Exp $

include ../../../../Makefile.include


vpath %.class $(CLASSDIR)/blocks



CLASSES=ConnectionTable.class			\
	DistributedHashtable.class		\
	ReplicatedHashtable.class		\
	ReplicatedTree.class			\
	DistributedLockManager.class		\
	DistributedTree.class			\
	GroupRequest.class			\
	Link.class				\
	LockingException.class			\
	LockManager.class			\
	LogicalLink.class			\
	MessageDispatcher.class			\
	MessageListenerAdapter.class		\
	MethodCall.class			\
	MethodLookup.class			\
	MethodLookupClos.class			\
	MethodLookupJava.class			\
	NotificationBus.class			\
	PullPushAdapter.class			\
	ReplicationData.class			\
	ReplicationManager.class		\
	ReplicationReceiver.class		\
	RequestCorrelator.class			\
	RequestHandler.class			\
	RpcDispatcher.class			\
	RspCollector.class			\
	TransactionalHashtable.class		\
        TwoPhaseVotingAdapter.class		\
        TwoPhaseVotingListener.class		\
	UpdateException.class			\
	VotingAdapter.class			\
	VotingListener.class			\
	Xid.class


all: $(CLASSES)



clean: 
	@rm -f $(CLASSDIR)/blocks/*.class *~






