## $Id: Makefile,v 1.1.1.1 2003/09/09 01:24:09 belaban Exp $

include ../../../../Makefile.include

vpath %.class $(CLASSDIR)/debug

CLASSFILES=Profiler.class			\
	   Debugger.class			\
	   ProtocolView.class			\
	   QUEUEView.class			\
           ProtocolSpecificView.class		\
	   ProtocolTester.class


all: $(CLASSFILES)



clean: 
	@rm -f $(CLASSDIR)/debug/*.class *~ core








