## $Id: Makefile,v 1.1.1.1 2003/09/09 01:24:09 belaban Exp $

include ../../../../../Makefile.include

vpath %.class $(CLASSDIR)/demos/wb

CLASSES=Whiteboard.class UserInfoDialog.class Node.class SendDialog.class MessageDialog.class\
      GraphPanel.class


all: $(CLASSES)


clean: 
	@rm -f $(CLASSDIR)/demos/wb/*.class *~ core





