## $Id: Makefile,v 1.1.1.1 2003/09/09 01:24:12 belaban Exp $

include ../../../../../../Makefile.include

vpath %.class $(CLASSDIR)/service/lease

CLASSFILES=LeaseFactoryClientTest.class


all: $(CLASSFILES)



clean: 
	@rm -f $(CLASSDIR)/service/lease/*.class *~ core
