## $Id: Makefile,v 1.1 2003/09/09 01:24:09 belaban Exp $

include ../../../../Makefile.include


vpath %.class $(CLASSDIR)/log

CLASSES=Format.class				\
	Tracer.class				\
	NetworkTracer.class			\
	PrintStreamTracer.class			\
	SystemTracer.class			\
	SystemErrTracer.class			\
	SystemOutTracer.class			\
	WriterTracer.class			\
	Trace.class



all: $(CLASSES)



clean: 
	@rm -f $(CLASSDIR)/log/*.class *~






