#!/bin/bash


export CLASSPATH=$CLASSPATH:../../../../lib/junit.jar

echo ""

echo "Running NakReceiverWindowTest:"
java org.javagroups.tests.NakReceiverWindowTest
echo ""


echo "Running ViewIdTest:"
java org.javagroups.tests.ViewIdTest
echo ""

echo "Running ViewTest:"
java org.javagroups.tests.ViewTest
echo ""

echo "Running CommonTest:"
java org.javagroups.tests.CommonTest
echo ""

echo "Running IpAddressTest:"
java org.javagroups.tests.IpAddressTest
echo ""

echo "Running MembershipTest:"
java org.javagroups.tests.MembershipTest
echo ""

echo "Running DigestTest:"
java org.javagroups.tests.DigestTest
echo ""

echo "Running FragTest:"
java org.javagroups.tests.FragTest
echo ""

echo "Running QueueTest:"
java org.javagroups.tests.QueueTest
echo ""

echo "Running InterruptTest:"
java org.javagroups.tests.InterruptTest
echo ""

#echo "Running NakackTest:"
#java org.javagroups.tests.NakackTest
#echo ""

