## $Id: Makefile,v 1.1.1.1 2003/09/09 01:24:09 belaban Exp $

include ../../../../Makefile.include

vpath %.class $(CLASSDIR)/persistence



CLASSES=CannotConnectException.class		\
	CannotCreateSchemaException.class	\
	CannotPersistException.class		\
	CannotRemoveException.class		\
	CannotRetrieveException.class		\
	DBPersistenceManager.class		\
	FilePersistenceManager.class		\
	PersistenceFactory.class		\
	PersistenceManager.class



this: $(CLASSES)



clean: 
	@rm -f $(CLASSDIR)/util/*.class *~






