## $Id: Makefile,v 1.1 2003/09/09 01:24:11 belaban Exp $

include ../../../../../Makefile.include

vpath %.class $(CLASSDIR)/protocols/ring

CLASSFILES=RingNode.class			\
	   RingNodeFlowControl.class		\
	   RingToken.class			\
           TcpRingNode.class			\
           TokenLostException.class		\
           UdpRingNode.class


all: $(CLASSFILES)



clean: 
	@rm -f $(CLASSDIR)/protocols/ring/*.class *~ core







