## $Id: Makefile,v 1.1 2003/09/09 01:24:12 belaban Exp $

include ../../../../../Makefile.include

vpath %.class $(CLASSDIR)/service/lease



CLASSES=DenyResponseHeader.class		\
	Lease.class				\
	LeaseDeniedException.class		\
	LeaseException.class			\
	LeaseFactory.class			\
	LeaseFactoryClient.class		\
        LeaseFactoryService.class		\
	LeaseInfoReplicationHeader.class	\
	LeaseRequestHeader.class		\
	LeaseResponseHeader.class		\
	RecursiveLeaseRequestException.class	\
	UnknownLeaseException.class



this: $(CLASSES)



clean: 
	@rm -f $(CLASSDIR)/service/lease/*.class *~






