## $Id: Makefile,v 1.1 2003/09/09 01:24:09 belaban Exp $

include ../../../../Makefile.include

vpath %.class $(CLASSDIR)/ensemble

CLASSFILES=Hot_Buffer.class Hot_Callbacks.class Hot_Endpoint.class Hot_Ensemble.class\
	   Hot_Error.class Hot_GroupContext.class Hot_IO_Controller.class\
	   Hot_JoinOps.class Hot_Message.class Hot_Mutex.class Hot_ObjectMessage.class\
	   Hot_ViewID.class Hot_ViewState.class


all: $(CLASSFILES)



clean: 
	@rm -f $(CLASSDIR)/ensemble/*.class *~ core





